### ISSUE TITLE
iOS notifications are not displayed when running the app

### ISSUE THREAD

**Issue by djc2k** [Pushwoosh/phonegap-cordova-push-notifications#46]
When we are not running our app; e.g., in the main screen or in some other app, the notification will appear in the notification bar.  However, if we are running our app, the notification will not show up.   We are testing on iOS 7.0.4.

Please advise.

Dave

**Comment by Wang0620** [comment]
Hope you are doing well. I am using Pushwoosh cordova plugin for Android and iOS apps. I am just wondering if hwid is always unique for iOS device, so I can use to detect special ios device with it? It will be changed for any circumstances? In that case, I will not be able to use hwid as unique device id for iOS device. Thanks for your great help. 

Sincerely

**Comment by shaders** [comment]
@Wang0620 please open a new issue for this.

**Comment by Wang0620** [comment]
I've just opened new issue. Please take a look at and let me know. 
https://github.com/Pushwoosh/phonegap-cordova-push-notifications/issues/60
Thanks
