### ISSUE TITLE
Notifications foreground == true when they should not be

### ISSUE THREAD

**Issue by abulte** [Pushwoosh/phonegap-cordova-push-notifications#56]
Hi,

I have a problem on my production Android app which I don't have on my dev and staging apps. I use the Pushwoosh phonegap plugin to receive notifications on those apps.

When a user clicks on a notification with the production app in background, it comes back in my app with the property `foreground` set to true. I'm expecting false since the app is in background, and this is what I get on my dev and staging apps but not on production.

Any idea why this might happen? The only difference between dev/staging and production is that the app is debbugable on dev/staging and is instrumented by the TestFairy SDK.

Thanks in advance.

**Comment by nokturnal** [comment]
I am finding (at least on Android) that if the app is closed and a push is received, that is the only case when foreground = false.  If the app is in the background when a push is received, it states foreground = true...

**Comment by shaders** [comment]
I would recommend ignoring this flag. It is unreliable. The only reliable way to get if the app is on foreground is to use ActivityLifecycleCallbacks.  

http://developer.android.com/reference/android/app/Application.html#registerActivityLifecycleCallbacks%28android.app.Application.ActivityLifecycleCallbacks%29  

However it is available only from API level 14.

**Comment by nokturnal** [comment]
Sadly, I am using the Cordova/Pushwoosh plugin and am left with only the data exposed by it.  What would be the best be method (if any) to reliably get the accurate background/foreground state of a notification by using only the cordova/pushwoosh plugin?
