### ISSUE TITLE
How to send Pushwoosh notifications to Wiziapp apps

### ISSUE THREAD

**Issue by Gaviniso** [Pushwoosh/phonegap-cordova-push-notifications#57]
We have set-up Pushwoosh to send schedule notifications to an Android and iOS app made with Wiziapp.

But the push notifications are not working.

I seem to have set-up my iOS and Android apps correctly an my 4 test Wooshes are being sent but not being received by my iPhone nor Android phone. I am in Production mode (as I am not a coder and the apps are aldready live).

The apps are "native" made by Wiziapp plugin in WP. I have turned off their push notification settings on the plugin, remade and uploaded the Android APK in Google Console and revoked the existing iOS Production certificate (and made a new one).

**Comment by shaders** [comment]
What does "push status" say?

**Comment by Gaviniso** [comment]
"Done".

Here are the details for one of the test Wooshes:

Message ID: 1188305950
Code:DCC4-624DD766-6548A3FC
Type:broadcast
Send date:2015-02-25 13:06:47
Create date:2015-02-25 13:06:47
Platforms: 
Status:done
Source:CP
Timezone-sensitive:No

**Comment by shaders** [comment]
Sorry, this is not support forum. You can ask support team by using contact form on the website.
This is only for SDK/Dev/Code discussions.
