### ISSUE TITLE
Failed to Register - Android/Cordova

### ISSUE THREAD

**Issue by aschalund** [Pushwoosh/phonegap-cordova-push-notifications#58]
Having an issue where i get 
<code>04-13 11:27:39.596    7722-7761/com.fisher.fairplay W/System.err﹕ org.json.JSONException: Index 0 out of range [0..0)
04-13 11:27:39.598    7722-7761/com.fisher.fairplay W/System.err﹕ at org.json.JSONArray.get(JSONArray.java:282)
04-13 11:27:39.598    7722-7761/com.fisher.fairplay W/System.err﹕ at org.json.JSONArray.getJSONObject(JSONArray.java:510)
04-13 11:27:39.599    7722-7761/com.fisher.fairplay W/System.err﹕ at com.pushwoosh.plugin.pushnotifications.PushNotifications.internalRegister(PushNotifications.java:145)
04-13 11:27:39.600    7722-7761/com.fisher.fairplay W/System.err﹕ at com.pushwoosh.plugin.pushnotifications.PushNotifications.execute(PushNotifications.java:358)
04-13 11:27:39.601    7722-7761/com.fisher.fairplay W/System.err﹕ at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:84)
04-13 11:27:39.601    7722-7761/com.fisher.fairplay W/System.err﹕ at org.apache.cordova.PluginManager.exec(PluginManager.java:147)
04-13 11:27:39.602    7722-7761/com.fisher.fairplay W/System.err﹕ at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
04-13 11:27:39.602    7722-7761/com.fisher.fairplay W/System.err﹕ at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:40)
04-13 11:27:39.603    7722-7761/com.fisher.fairplay W/System.err﹕ at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
04-13 11:27:39.604    7722-7761/com.fisher.fairplay W/System.err﹕ at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
04-13 11:27:39.604    7722-7761/com.fisher.fairplay W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
04-13 11:27:39.605    7722-7761/com.fisher.fairplay W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
04-13 11:27:39.605    7722-7761/com.fisher.fairplay W/System.err﹕ at android.os.HandlerThread.run(HandlerThread.java:61)
04-13 11:27:39.661    7722-7722/com.fisher.fairplay D/CordovaLog﹕ file:///android_asset/www/js/index.js: Line 26 : initPushwooshAndroid
04-13 11:27:39.661    7722-7722/com.fisher.fairplay I/chromium﹕ [INFO:CONSOLE(26)] "initPushwooshAndroid", source: file:///android_asset/www/js/index.js (26)
04-13 11:27:39.661    7722-7722/com.fisher.fairplay D/CordovaLog﹕ file:///android_asset/www/js/index.js: Line 51 : ["failed to register ","Index 0 out of range [0..0)"]
04-13 11:27:39.661    7722-7722/com.fisher.fairplay I/chromium﹕ [INFO:CONSOLE(51)] "["failed to register ","Index 0 out of range [0..0)"]", source: file:///android_asset/www/js/index.js (51)</code>

Any suggestions?

**Comment by shaders** [comment]
Which plugin version do you use?

com.pushwoosh.plugin.pushnotifications.PushNotifications.internalRegister(PushNotifications.java:145) doesnt match the file:  

https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/blob/master/src/android/src/com/pushwoosh/plugin/pushnotifications/PushNotifications.java

**Comment by aschalund** [comment]
I had pulled https://www.pushwoosh.com/programming-push-notification/android/android-additional-platforms/phonegapcordova-sdk-integration/ for my plugin version.

Just reverted back to that version and get 

/src/com/pushwoosh/plugin/pushnotifications/PushNotifications.java
Error:(28, 37) java: cannot find symbol
  symbol:   class PushPersistance
  location: package com.arellomobile.android.push
Error:(29, 49) java: cannot find symbol
  symbol:   class GetTagsListener
  location: class com.arellomobile.android.push.PushManager
Error:(30, 37) java: cannot find symbol
  symbol:   class SendPushTagsCallBack
  location: package com.arellomobile.android.push
Error:(35, 48) java: package com.arellomobile.android.push.utils.rich does not exist
Error:(175, 36) java: cannot find symbol
  symbol:   method initializePushManager(android.app.Activity,java.lang.String,java.lang.String)
  location: class com.arellomobile.android.push.PushManager
Error:(176, 51) java: cannot find symbol
  symbol:   method getInstance(android.app.Activity)
  location: class com.arellomobile.android.push.PushManager
Error:(191, 37) java: cannot find symbol
  symbol:   method registerForPushNotifications()
  location: variable mPushManager of type com.arellomobile.android.push.PushManager
Error:(330, 61) java: cannot find symbol
  symbol:   class SendPushTagsCallBack
  location: class com.pushwoosh.plugin.pushnotifications.PushNotifications
Error:(332, 25) java: method does not override or implement a method from a supertype
Error:(343, 25) java: method does not override or implement a method from a supertype
Error:(354, 25) java: method does not override or implement a method from a supertype
Error:(358, 72) java: incompatible types: SendTagsListenerImpl cannot be converted to com.arellomobile.android.push.tags.SendPushTagsCallBack
Error:(372, 55) java: cannot find symbol
  symbol:   method getPushToken(android.app.Activity)
  location: class com.arellomobile.android.push.PushManager
Error:(378, 55) java: cannot find symbol
  symbol:   method getPushwooshHWID(android.app.Activity)
  location: class com.arellomobile.android.push.PushManager
Error:(438, 37) java: cannot find symbol
  symbol:   method startTrackingBeaconPushes()
  location: variable mPushManager of type com.arellomobile.android.push.PushManager
Error:(449, 37) java: cannot find symbol
  symbol:   method stopTrackingBeaconPushes()
  location: variable mPushManager of type com.arellomobile.android.push.PushManager
Error:(458, 44) java: cannot find symbol
  symbol:   method setBeaconBackgroundMode(android.app.Activity,boolean)
  location: class com.arellomobile.android.push.PushManager
Error:(603, 48) java: cannot find symbol
  symbol:   variable RichPushUtils
  location: class com.pushwoosh.plugin.pushnotifications.PushNotifications
Error:(604, 44) java: cannot find symbol
  symbol:   method setColorLED(android.app.Activity,int)
  location: class com.arellomobile.android.push.PushManager
Error:(655, 68) java: cannot find symbol
  symbol:   class GetTagsListener
  location: class com.pushwoosh.plugin.pushnotifications.PushNotifications
Error:(657, 33) java: method does not override or implement a method from a supertype
Error:(668, 33) java: method does not override or implement a method from a supertype
Error:(680, 36) java: cannot find symbol
  symbol:   method getTagsAsync(android.app.Activity,GetTagsListenerImpl)
  location: class com.arellomobile.android.push.PushManager
Error:(686, 57) java: cannot find symbol
  symbol:   variable PushPersistance
  location: class com.pushwoosh.plugin.pushnotifications.PushNotifications
Error:(693, 25) java: cannot find symbol
  symbol:   variable PushPersistance
  location: class com.pushwoosh.plugin.pushnotifications.PushNotifications
Error:(699, 36) java: cannot find symbol
  symbol:   method clearNotificationCenter(android.app.Activity)
  location: class com.arellomobile.android.push.PushManager


Noticed that it is unable to resolve the following
import com.arellomobile.android.push.PushPersistance;
import com.arellomobile.android.push.PushManager.GetTagsListener;
import com.arellomobile.android.push.SendPushTagsCallBack;
import com.arellomobile.android.push.utils.rich.RichPushUtils;

I uninstalled the plugin via CLI and installed again and this is where I am stuck at the moment. Seems like I am missing some files?

**Comment by shaders** [comment]
Somehow you broke the plugin installation. What command "cordova plugin list" says?

**Comment by aschalund** [comment]
com.pushwoosh.plugins.pushwoosh 3.4.16 "Pushwoosh"

and the rest of the plugins i am running.

**Comment by shaders** [comment]
From the logs I see pushwoosh.jar library disappeared somewhere. What happens if you remove plugin (cordova plugin remove command) and reinstall again?

**Comment by aschalund** [comment]
Same issue. I can see that the Pushwoosh.jar file is located in my /libs directory.

**Comment by shaders** [comment]
I'm sorry, the same - 1st one or the 2nd one?

**Comment by aschalund** [comment]
My apologies I was not clear. Uninstalling/reinstalling the plugin results in the 2nd error log i posted. I do see the jar file within my /libs directory. 

cordova_plugins.js  adds in 
{
        "file": "plugins/com.pushwoosh.plugins.pushwoosh/www/PushNotification.js",
        "id": "com.pushwoosh.plugins.pushwoosh.PushNotification",
        "clobbers": [
            "plugins.pushNotification"
        ]
    }
and 
module.exports.metadata = 
// TOP OF METADATA
{
    "com.pushwoosh.plugins.pushwoosh": "3.4.16"
}
// BOTTOM OF METADATA

config.xml
 <feature name="PushNotification">
        <param name="android-package" onload="true" value="com.pushwoosh.plugin.pushnotifications.PushNotifications" />
    </feature>

AndroidManifest.xml
 <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="com.phonegap.hello_world.MESSAGE" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter>
                <action android:name="com.fisher.fairplay.MESSAGE" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <activity android:name="com.arellomobile.android.push.PushWebview" />
        <activity android:name="com.arellomobile.android.push.MessageActivity" />
        <activity android:name="com.arellomobile.android.push.PushHandlerActivity" />
        <activity android:label="@string/app_name" android:name="com.facebook.LoginActivity" />
        <receiver android:name="com.google.android.gcm.GCMBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="com.fisher.fairplay" />
            </intent-filter>
        </receiver>
        <service android:name="com.arellomobile.android.push.PushGCMIntentService" />
        <service android:name="com.arellomobile.android.push.GeoLocationService" />
        <receiver android:name="com.arellomobile.android.push.AlarmReceiver" />
    </application>
    <uses-sdk android:minSdkVersion="10" android:targetSdkVersion="18" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <permission android:name="com.phonegap.hello_world.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="com.phonegap.hello_world.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <permission android:name="com.fisher.fairplay.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="com.fisher.fairplay.permission.C2D_MESSAGE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
</manifest>

**Comment by aschalund** [comment]
Alright so I ended up just rebuild the app completely from scratch. New gradle build and everything and now I can get the plugin to work. There had to be something jacked up in the original gradle that was messing with the plugin.

Thanks for the help!
