### ISSUE TITLE
Cordova Pushwoosh plugin HWID is changed for iOS and Android? 

### ISSUE THREAD

**Issue by Wang0620** [Pushwoosh/phonegap-cordova-push-notifications#60]
Hope you are doing well. I am using Pushwoosh cordova plugin for Android and iOS apps. I am just wondering if hwid is always unique for iOS device, so I can use to detect special ios device with it? It will be changed for any circumstances? In that case, I will not be able to use hwid as unique device id for iOS device. Thanks for your great help.

Sincerely

**Comment by shaders** [comment]
Pushwoosh uses the following HWID algorithm:

1. If you link to AdSupport.framework it will user Advertisement Identifier. This identifier is unique for the device and is the same for all apps installed. The only way for this identifier to change is when user forces it to change in the option deeply buried somewhere in device settings.

2. If you do not link to AdSupport.framework, Identifier for Vendor would be used. This identifier is unique for the device but will change between the apps if they are signed with different Apple Developer Certificate. Basically it will be different for different Apple Developer Accounts. 

You can read more about in the Apple Docs
https://developer.apple.com/library/ios/documentation/AdSupport/Reference/ASIdentifierManager_Ref/index.html#//apple_ref/occ/instp/ASIdentifierManager/advertisingIdentifier:

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIDevice_Class/index.html#//apple_ref/occ/instp/UIDevice/identifierForVendor

Also some useful links on this identifiers:
http://stackoverflow.com/questions/13855990/are-there-other-factors-besides-device-and-app-vendor-that-determine-the-ident

http://stackoverflow.com/questions/11836225/ios6-udid-what-advantages-does-identifierforvendor-have-over-identifierforadve
