### ISSUE TITLE
iOS Build Error

### ISSUE THREAD

**Issue by PgsHC** [Pushwoosh/phonegap-cordova-push-notifications#64]
Hi,
I get build error 65 with the plugin installed.
> Command finished with error code 65: xcodebuild -workspace,XXX.xcworkspace,-scheme,XXX,-configuration,Release,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 12 Pro Max,build,CONFIGURATION_BUILD_DIR=/Users/xx/GitHub/xx/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/xx/GitHub/xx/platforms/ios/build/sharedpch
>xcodebuild: Command failed with exit code 65
> Error: xcodebuild: Command failed with exit code 65
>    at ChildProcess.whenDone (/Users/xxx/GitHub/xx/node_modules/cordova-common/src/superspawn.js:136:25)
>    at ChildProcess.emit (events.js:315:20)
>    at maybeClose (internal/child_process.js:1048:16)
>    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
>[ERROR] An error occurred while running subprocess cordova.

I've tried plugin latest and latest-1 versions.
Here my conf :

> Ionic:
>
>   Ionic CLI                     : 6.9.2 (/usr/local/lib/node_modules/@ionic/cli)
>   Ionic Framework               : @ionic/angular 5.4.1
>   @angular-devkit/build-angular : 0.1000.8
>   @angular-devkit/schematics    : 10.0.8
>   @angular/cli                  : 10.0.8
>   @ionic/angular-toolkit        : 2.3.3
>
> Cordova:
>
>   Cordova CLI       : 10.0.0
>   Cordova Platforms : android 9.0.0, ios 6.2.0
>   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 7 other plugins)
>
>Utility:
>
>   cordova-res (update available: 0.15.3) : 0.11.0
>   native-run                             : 1.3.0
>
> System:
>
>   Android SDK Tools : 26.1.1 (/Users/xx/Library/Android/sdk)
>   ios-sim           : 8.0.2
>   NodeJS            : v14.15.0 (/Users/xx/.nvm/versions/node/v14.15.0/bin/node)
>   npm               : 6.14.8
>   OS                : macOS
>   Xcode             : Xcode 12.4 Build version 12D4e

Plugin list 
> cordova-plugin-customurlscheme 5.0.2 "Custom URL scheme"
> cordova-plugin-device 2.0.2 "Device"
> cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
> cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
> cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
> cordova-plugin-network-information 2.0.2 "Network Information"
> cordova-plugin-statusbar 2.4.2 "StatusBar"
> cordova-plugin-whitelist 1.3.3 "Whitelist"
> ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
> pushwoosh-cordova-plugin 7.18.8 "Pushwoosh"`

Build can be acheived in two way : 
- remove the pushwoosh plugin 
- use --buildFlag="-UseModernBuildSystem=0"

Work without the --prod

Any clue ?

Thanks

**Comment by wfhm** [comment]
@PegaseHC Error 65 is a generic error that simply describes that **xcodebuild** couldn't do a build, and pretty much anything could be the reason for it. By any chance could you please try building the app with Xcode GUI to get a more meaningful error description?

**Comment by PegaseHC** [comment]
@wfhm after npm update to 7.5.6 I din't get error...
